name = input("Enter name: ")
gender = input("Enter gender: ")
age = input("Enter age: ")
address = input("Enter address: ")
print("----------------------")
print(f"Name: {name}")
print(f"Gender: {gender}")
print(f"Age: {age}")
print(f"Address: {address}")
